// Code generated by girgen. DO NOT EDIT.

package javascriptcore

import ()

// #include <stdlib.h>
// #include <jsc/jsc.h>
import "C"

// Executor: function passed to jsc_value_new_promise called during
// initialization
//
// It is called like a JavaScript function, so exceptions raised will not be
// propagated to the context, but handled by the promise causing a rejection.
// resolve and reject can be reffed for later use to handle async task
// completion.
type Executor func(resolve, reject *Value)
