// Code generated by girgen. DO NOT EDIT.

package javascriptcore

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <jsc/jsc.h>
import "C"

//export _gotk4_javascriptcore6_Executor
func _gotk4_javascriptcore6_Executor(arg1 *C.JSCValue, arg2 *C.JSCValue, arg3 C.gpointer) {
	var fn Executor
	{
		v := gbox.Get(uintptr(arg3))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(Executor)
	}

	var _resolve *Value // out
	var _reject *Value  // out

	_resolve = wrapValue(coreglib.Take(unsafe.Pointer(arg1)))
	_reject = wrapValue(coreglib.Take(unsafe.Pointer(arg2)))

	fn(_resolve, _reject)
}
