// Code generated by girgen. DO NOT EDIT.

package webkit2

import (
	"fmt"
	"runtime"
	"strings"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <webkit2/webkit2.h>
import "C"

// GType values.
var (
	GTypeWebExtensionMatchPatternOptions = coreglib.Type(C.webkit_web_extension_match_pattern_options_get_type())
	GTypeWebExtensionMatchPattern        = coreglib.Type(C.webkit_web_extension_match_pattern_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeWebExtensionMatchPatternOptions, F: marshalWebExtensionMatchPatternOptions},
		coreglib.TypeMarshaler{T: GTypeWebExtensionMatchPattern, F: marshalWebExtensionMatchPattern},
	})
}

// WebExtensionMatchPatternOptions: enum values representing matching options.
type WebExtensionMatchPatternOptions C.guint

const (
	// WebExtensionMatchPatternOptionsNone: no special matching options.
	WebExtensionMatchPatternOptionsNone WebExtensionMatchPatternOptions = 0b1
	// WebExtensionMatchPatternOptionsIgnoreSchemes: scheme components should be
	// ignored while matching.
	WebExtensionMatchPatternOptionsIgnoreSchemes WebExtensionMatchPatternOptions = 0b10
	// WebExtensionMatchPatternOptionsIgnorePaths: host components should be
	// ignored while matching.
	WebExtensionMatchPatternOptionsIgnorePaths WebExtensionMatchPatternOptions = 0b100
	// WebExtensionMatchPatternOptionsMatchBidirectionally: two patterns should
	// be checked in either direction while matching (A matches B, or B matches
	// A). Invalid for matching URLs.
	WebExtensionMatchPatternOptionsMatchBidirectionally WebExtensionMatchPatternOptions = 0b1000
)

func marshalWebExtensionMatchPatternOptions(p uintptr) (interface{}, error) {
	return WebExtensionMatchPatternOptions(coreglib.ValueFromNative(unsafe.Pointer(p)).Flags()), nil
}

// String returns the names in string for WebExtensionMatchPatternOptions.
func (w WebExtensionMatchPatternOptions) String() string {
	if w == 0 {
		return "WebExtensionMatchPatternOptions(0)"
	}

	var builder strings.Builder
	builder.Grow(175)

	for w != 0 {
		next := w & (w - 1)
		bit := w - next

		switch bit {
		case WebExtensionMatchPatternOptionsNone:
			builder.WriteString("None|")
		case WebExtensionMatchPatternOptionsIgnoreSchemes:
			builder.WriteString("IgnoreSchemes|")
		case WebExtensionMatchPatternOptionsIgnorePaths:
			builder.WriteString("IgnorePaths|")
		case WebExtensionMatchPatternOptionsMatchBidirectionally:
			builder.WriteString("MatchBidirectionally|")
		default:
			builder.WriteString(fmt.Sprintf("WebExtensionMatchPatternOptions(0b%b)|", bit))
		}

		w = next
	}

	return strings.TrimSuffix(builder.String(), "|")
}

// Has returns true if w contains other.
func (w WebExtensionMatchPatternOptions) Has(other WebExtensionMatchPatternOptions) bool {
	return (w & other) == other
}

// WebExtensionMatchPattern represents a way to specify a group of URLs for use
// in WebExtensions.
//
// All match patterns are specified as strings. Apart from the special
// <all_urls> pattern, match patterns consist of three parts: scheme, host,
// and path.
//
// Generally, match patterns are returned from a KitWebExtension.
//
// An instance of this type is always passed by reference.
type WebExtensionMatchPattern struct {
	*webExtensionMatchPattern
}

// webExtensionMatchPattern is the struct that's finalized.
type webExtensionMatchPattern struct {
	native *C.WebKitWebExtensionMatchPattern
}

func marshalWebExtensionMatchPattern(p uintptr) (interface{}, error) {
	b := coreglib.ValueFromNative(unsafe.Pointer(p)).Boxed()
	return &WebExtensionMatchPattern{&webExtensionMatchPattern{(*C.WebKitWebExtensionMatchPattern)(b)}}, nil
}

// NewWebExtensionMatchPatternAllHostsAndSchemes constructs a struct WebExtensionMatchPattern.
func NewWebExtensionMatchPatternAllHostsAndSchemes() *WebExtensionMatchPattern {
	var _cret *C.WebKitWebExtensionMatchPattern // in

	_cret = C.webkit_web_extension_match_pattern_new_all_hosts_and_schemes()

	var _webExtensionMatchPattern *WebExtensionMatchPattern // out

	_webExtensionMatchPattern = (*WebExtensionMatchPattern)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_webExtensionMatchPattern)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.webkit_web_extension_match_pattern_unref((*C.WebKitWebExtensionMatchPattern)(intern.C))
		},
	)

	return _webExtensionMatchPattern
}

// NewWebExtensionMatchPatternAllUrls constructs a struct WebExtensionMatchPattern.
func NewWebExtensionMatchPatternAllUrls() *WebExtensionMatchPattern {
	var _cret *C.WebKitWebExtensionMatchPattern // in

	_cret = C.webkit_web_extension_match_pattern_new_all_urls()

	var _webExtensionMatchPattern *WebExtensionMatchPattern // out

	_webExtensionMatchPattern = (*WebExtensionMatchPattern)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_webExtensionMatchPattern)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.webkit_web_extension_match_pattern_unref((*C.WebKitWebExtensionMatchPattern)(intern.C))
		},
	)

	return _webExtensionMatchPattern
}

// NewWebExtensionMatchPatternWithScheme constructs a struct WebExtensionMatchPattern.
func NewWebExtensionMatchPatternWithScheme(scheme string, host string, path string) (*WebExtensionMatchPattern, error) {
	var _arg1 *C.gchar                          // out
	var _arg2 *C.gchar                          // out
	var _arg3 *C.gchar                          // out
	var _cret *C.WebKitWebExtensionMatchPattern // in
	var _cerr *C.GError                         // in

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(scheme)))
	defer C.free(unsafe.Pointer(_arg1))
	_arg2 = (*C.gchar)(unsafe.Pointer(C.CString(host)))
	defer C.free(unsafe.Pointer(_arg2))
	_arg3 = (*C.gchar)(unsafe.Pointer(C.CString(path)))
	defer C.free(unsafe.Pointer(_arg3))

	_cret = C.webkit_web_extension_match_pattern_new_with_scheme(_arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(scheme)
	runtime.KeepAlive(host)
	runtime.KeepAlive(path)

	var _webExtensionMatchPattern *WebExtensionMatchPattern // out
	var _goerr error                                        // out

	if _cret != nil {
		_webExtensionMatchPattern = (*WebExtensionMatchPattern)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_webExtensionMatchPattern)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.webkit_web_extension_match_pattern_unref((*C.WebKitWebExtensionMatchPattern)(intern.C))
			},
		)
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _webExtensionMatchPattern, _goerr
}

// NewWebExtensionMatchPatternWithString constructs a struct WebExtensionMatchPattern.
func NewWebExtensionMatchPatternWithString(str string) (*WebExtensionMatchPattern, error) {
	var _arg1 *C.gchar                          // out
	var _cret *C.WebKitWebExtensionMatchPattern // in
	var _cerr *C.GError                         // in

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(str)))
	defer C.free(unsafe.Pointer(_arg1))

	_cret = C.webkit_web_extension_match_pattern_new_with_string(_arg1, &_cerr)
	runtime.KeepAlive(str)

	var _webExtensionMatchPattern *WebExtensionMatchPattern // out
	var _goerr error                                        // out

	if _cret != nil {
		_webExtensionMatchPattern = (*WebExtensionMatchPattern)(gextras.NewStructNative(unsafe.Pointer(_cret)))
		runtime.SetFinalizer(
			gextras.StructIntern(unsafe.Pointer(_webExtensionMatchPattern)),
			func(intern *struct{ C unsafe.Pointer }) {
				C.webkit_web_extension_match_pattern_unref((*C.WebKitWebExtensionMatchPattern)(intern.C))
			},
		)
	}
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _webExtensionMatchPattern, _goerr
}

// Host gets the host part of the pattern string, unless
// webkit_web_extension_match_pattern_get_matches_all_urls is TRUE.
//
// The function returns the following values:
//
//   - utf8: host string.
func (matchPattern *WebExtensionMatchPattern) Host() string {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret *C.gchar                          // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_host(_arg0)
	runtime.KeepAlive(matchPattern)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

// MatchesAllHosts gets whether the match pattern matches all host. This happens
// when the pattern is <all_urls>, or if * is set as the host string.
//
// The function returns the following values:
//
//   - ok: whether this match pattern matches all hosts.
func (matchPattern *WebExtensionMatchPattern) MatchesAllHosts() bool {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret C.gboolean                        // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_matches_all_hosts(_arg0)
	runtime.KeepAlive(matchPattern)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// MatchesAllUrls gets whether the match pattern matches all URLs, in other
// words, whether the pattern is <all_urls>.
//
// The function returns the following values:
//
//   - ok: whether this match pattern matches all URLs.
func (matchPattern *WebExtensionMatchPattern) MatchesAllUrls() bool {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret C.gboolean                        // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_matches_all_urls(_arg0)
	runtime.KeepAlive(matchPattern)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Path gets the path part of the pattern string, unless
// webextensionmatchpattern.GetMatchesAllUrls is TRUE.
//
// The function returns the following values:
//
//   - utf8: path string.
func (matchPattern *WebExtensionMatchPattern) Path() string {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret *C.gchar                          // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_path(_arg0)
	runtime.KeepAlive(matchPattern)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

// Scheme gets the scheme part of the pattern string, unless
// webkit_web_extension_match_pattern_get_matches_all_urls is TRUE.
//
// The function returns the following values:
//
//   - utf8: scheme string.
func (matchPattern *WebExtensionMatchPattern) Scheme() string {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret *C.gchar                          // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_scheme(_arg0)
	runtime.KeepAlive(matchPattern)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

// String gets the original pattern string.
//
// The function returns the following values:
//
//   - utf8: original pattern string.
func (matchPattern *WebExtensionMatchPattern) String() string {
	var _arg0 *C.WebKitWebExtensionMatchPattern // out
	var _cret *C.gchar                          // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))

	_cret = C.webkit_web_extension_match_pattern_get_string(_arg0)
	runtime.KeepAlive(matchPattern)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

// MatchesPattern matches the matchPattern against the specified pattern with
// options.
//
// The function takes the following parameters:
//
//   - pattern to match with matchPattern.
//   - options use while matching.
//
// The function returns the following values:
//
//   - ok: whether the pattern matches the specified pattern.
func (matchPattern *WebExtensionMatchPattern) MatchesPattern(pattern *WebExtensionMatchPattern, options WebExtensionMatchPatternOptions) bool {
	var _arg0 *C.WebKitWebExtensionMatchPattern       // out
	var _arg1 *C.WebKitWebExtensionMatchPattern       // out
	var _arg2 C.WebKitWebExtensionMatchPatternOptions // out
	var _cret C.gboolean                              // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))
	_arg1 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(pattern)))
	_arg2 = C.WebKitWebExtensionMatchPatternOptions(options)

	_cret = C.webkit_web_extension_match_pattern_matches_pattern(_arg0, _arg1, _arg2)
	runtime.KeepAlive(matchPattern)
	runtime.KeepAlive(pattern)
	runtime.KeepAlive(options)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// MatchesURL matches the matchPattern against the specified URL with options.
//
// The function takes the following parameters:
//
//   - url: URL to match against the pattern.
//   - options use while matching.
//
// The function returns the following values:
//
//   - ok: whether the pattern matches the specified URL.
func (matchPattern *WebExtensionMatchPattern) MatchesURL(url string, options WebExtensionMatchPatternOptions) bool {
	var _arg0 *C.WebKitWebExtensionMatchPattern       // out
	var _arg1 *C.gchar                                // out
	var _arg2 C.WebKitWebExtensionMatchPatternOptions // out
	var _cret C.gboolean                              // in

	_arg0 = (*C.WebKitWebExtensionMatchPattern)(gextras.StructNative(unsafe.Pointer(matchPattern)))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(url)))
	defer C.free(unsafe.Pointer(_arg1))
	_arg2 = C.WebKitWebExtensionMatchPatternOptions(options)

	_cret = C.webkit_web_extension_match_pattern_matches_url(_arg0, _arg1, _arg2)
	runtime.KeepAlive(matchPattern)
	runtime.KeepAlive(url)
	runtime.KeepAlive(options)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// WebExtensionMatchPatternRegisterCustomURLScheme registers a custom URL scheme
// that can be used in match patterns.
//
// This method should be used to register any custom URL schemes used by the app
// for the extension base URLs, other than webkit-extension, or if extensions
// should have access to other supported URL schemes when using <all_urls>.
//
// The function takes the following parameters:
//
//   - urlScheme: custom URL scheme to register.
func WebExtensionMatchPatternRegisterCustomURLScheme(urlScheme string) {
	var _arg1 *C.gchar // out

	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(urlScheme)))
	defer C.free(unsafe.Pointer(_arg1))

	C.webkit_web_extension_match_pattern_register_custom_URL_scheme(_arg1)
	runtime.KeepAlive(urlScheme)
}
