// Code generated by girgen. DO NOT EDIT.

package soup

import (
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #include <stdlib.h>
// #include <libsoup/soup.h>
import "C"

func WebsocketErrorGetQuark() glib.Quark {
	var _cret C.GQuark // in

	_cret = C.soup_websocket_error_get_quark()

	var _quark glib.Quark // out

	_quark = glib.Quark(_cret)

	return _quark
}
